services:
  flask-app:
    container_name: assignment-5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - DB_NAME=dp_name
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_HOST=db # DO NOT CHANGE THIS HOST!
    depends_on:
      - db
  db:
    image: postgres:16.2-alpine
    container_name: assignment-5-db
    restart: always
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      # <Port exposed> : <Postgres Port running inside container> (Postgres expects port: 5432)
      - 5432:5433
    # A SQL dump is used for populatinig DB upon creation
    volumes:
      - ./test_db.sql:/docker-entrypoint-initdb.d/dump.sql
